# Generated by Django 4.2.1 on 2023-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_client_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='street_address_extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
