# Generated by Django 4.2.1 on 2023-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_organizationprofile_street_address_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
