# Generated by Django 4.2.1 on 2023-06-03 09:30

from django.db import migrations
from tenant_users.tenants.utils import create_public_tenant
from django.conf import settings


def add_public_tenant(apps, schema_editor):
    create_public_tenant(domain_url=settings.PUBLIC_TENANT_DOMAIN_NAME, owner_email="admin@acadiumlab.com")


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_public_tenant)
    ]
